name: poke_prueba
description: "Proyecto Flutter para prueba Tecnica."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#f79c8c"
  image: assets/splash.png